logsBucket: gs://lifevideos-app-logs-bucket

options:
  logging: GCS_ONLY

steps:
  # Step 1: Pull the Docker image from the public registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'us-east1-docker.pkg.dev/ethertube/ethertube-docker-repository/ethertube:latest']

  # Step 2: Run SQL script to create a materialized view in the database
  - name: 'postgres'  # Use the official postgres image
    entrypoint: 'psql'
    args:
      - "${_DATABASE_URL}"
      - "-c"
      - |
          CREATE MATERIALIZED VIEW video_search_view AS
          SELECT v.id,
                 v."channelId",
                 v.title,
                 v.description,
                 v."thumbnailSrc",
                 c."name" AS channel_name,
                 c."avatarSrc",
                 setweight(to_tsvector('english', v.title), 'A') ||
                 setweight(to_tsvector('english', v.description), 'B') ||
                 setweight(to_tsvector('english', c."name"), 'C') AS search_vector
          FROM videos v, channels c 
          WHERE v."channelId" = c.id
            AND c.status = true
            AND v.status = true;
          CREATE INDEX idx_video_search_vector ON video_search_view USING gin(search_vector);
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'lifevideos-app',
        '--image', 'us-east1-docker.pkg.dev/ethertube/ethertube-docker-repository/ethertube:latest',
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',
        '--vpc-connector', 'lifevideos-vpc-connector',
        '--set-env-vars',
        'DATABASE_URL=${_DATABASE_URL},NEXTAUTH_URL=${_NEXTAUTH_URL},AUTH_SECRET=${_AUTH_SECRET},AUTH_GOOGLE_ID=${_AUTH_GOOGLE_ID},AUTH_GOOGLE_SECRET=${_AUTH_GOOGLE_SECRET},GCP_PROJECT_ID=${_GCP_PROJECT_ID},GCP_BUCKET_NAME=${_GCP_BUCKET_NAME},GCP_CLIENT_EMAIL=${_GCP_CLIENT_EMAIL},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_CUSTOMER_ID=${_STRIPE_CUSTOMER_ID},CLOUD_PLATFORM=${_CLOUD_PLATFORM}'
      ]
